name: Get workflow ids

on:
  workflow_dispatch:
    inputs:
      github-repo:
        description: 'GitHub repository name (e.g. "book000/my-weekly-dep-update")'
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get workflow ids
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token [PERSONAL_ACCESS_TOKEN]" \
            https://api.github.com/repos/${{ github.event.inputs.github-repo }}/actions/workflows
