name: Request dependencies update at every week

on:
  schedule:
    - cron: "0 0 * * 5" # 毎週金曜 09:00 JST
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    outputs:
      issue-number: ${{ steps.create-issue.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create issue
        uses: imjohnbo/issue-bot@v3
        id: create-issue
        with:
          assignees: "book000"
          title: "Weekly dependencies update - ${{ steps.date.outputs.date }}"
          labels: "WeeklyDependUpdate"
          close-previous: true
          linked-comments: true

      - name: Output issue number
        run: |
          echo "Issue Number: ${{ steps.create-issue.outputs.issue-number }}"

  request-dep-update:
    runs-on: ubuntu-latest
    needs: create-issue

    strategy:
      matrix:
        action:
          - '{ repo: "jaoafa/jaoweb-users", workflow_id: "dependencies-update.yml", ref: "master" }'
          - '{ repo: "jaoafa/jaoweb-bans", workflow_id: "dependencies-update.yml", ref: "master" }'
          - '{ repo: "jaoafa/jaoweb-admin", workflow_id: "dependencies-update.yml", ref: "master" }'
          - '{ repo: "jaoafa/jaoweb-admin-cp", workflow_id: "dependencies-update.yml", ref: "master" }'
          - '{ repo: "jaoafa/jaotanChatLogger3", workflow_id: "dependencies-update.yml", ref: "master" }'
          - '{ repo: "jaoafa/jaoweb-deploy", workflow_id: "dependencies-update.yml", ref: "master" }'
          - '{ repo: "jaoafa/discord-new-threads", workflow_id: "dependencies-update.yml", ref: "master" }'
          - '{ repo: "jaoafa/watch-emojis", workflow_id: "dependencies-update.yml", ref: "master" }'
          - '{ repo: "jaoafa/node-jaotan", workflow_id: "dependencies-update.yml", ref: "master" }'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Manage matrix
        id: manage-matrix
        run: |
          echo "::set-output name=repo::${{ fromJson(matrix.action).repo }}"
          echo "::set-output name=workflow_id::${{ fromJson(matrix.action).workflow_id }}"
          echo "::set-output name=ref::${{ fromJson(matrix.action).ref }}"

      - name: Dispatch workflow
        run: |
          curl \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/${{ steps.manage-matrix.outputs.repo }}/actions/workflows/${{ steps.manage-matrix.outputs.workflow_id }}/dispatches \
            -d "{ \"ref\": \"${{ steps.manage-matrix.outputs.ref }}\", \"inputs\": { \"exec-from\": \"https://github.com/book000/my-weekly-dep-update/issues/${{ needs.create-issue.outputs.issue-number }}\" } }"

      - name: Get workflow runs
        id: get-workflow-runs
        run: |
          url="https://api.github.com/repos/${{ steps.manage-matrix.outputs.repo }}/actions/workflows/${{ steps.manage-matrix.outputs.workflow_id }}/runs?per_page=1"
          echo "::set-output name=html_url::$(curl -fsSL "$url" | jq -r '.workflow_runs[0].html_url')"

      - name: Comment to issue
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ needs.create-issue.outputs.issue-number }}
          body: |
            # [`${{ steps.manage-matrix.outputs.repo }}`](https://github.com/${{ steps.manage-matrix.outputs.repo }})

            ${{ steps.get-workflow-runs.outputs.html_url }}

            - Workflow: `${{ steps.manage-matrix.outputs.workflow_id }}`
            - Ref: `${{ steps.manage-matrix.outputs.ref }}`

